apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openrct2-data
  namespace: openrct2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
